template("js_library") {
  group(target_name) {
    if (defined(invoker.deps)) {
      deps = invoker.deps
    }
  }
}

template("js_binary") {
  group(target_name) {
    if (defined(invoker.deps)) {
      deps = invoker.deps
    }
  }
}

template("js_type_check") {
  group(target_name) {
    if (defined(invoker.deps)) {
      deps = invoker.deps
    }
  }
}

template("build_closure") {
  group(target_name) {
    if (defined(invoker.deps)) {
      deps = invoker.deps
    }
  }
}
